### ISSUE TITLE
Support for v3 not released yet?

### ISSUE THREAD

**Issue by micha149** [floriangaechter/gatsby-plugin-linkedin-insight#4]
Hey there. I'm currently updating a gatsby site from v2 to v3. I saw your commit, where you update the peer dependencies to include v3 but it seems not to be released yet. Any idea when the v3 support will be available?

**Comment by bogdancss** [comment]
any updates on this?

**Comment by tmttn** [comment]
Since this question has not been answered for so long (6 months)... I have taken it upon myself to fork & publish this plugin:

* https://github.com/tmttn/gatsby-plugin-linkedin-insight
* https://www.npmjs.com/package/@tmttn/gatsby-plugin-linkedin-insight

@floriangaechter I have credited you as the original creator of the plugin. If you ever intend to pick this plugin up again... please let me know, so I can deprecate the fork and redirect users of the plugin back to you.

My motivation for doing this is that we kinda need this functionality for our own project, but we are on Gatsby V3. I have released a `v1.0.2` version under `@tmttn/gatsby-plugin-linkedin-insight` that includes the updated peer dependencies for Gatsby V3.

**Comment by floriangaechter** [comment]
Hey! I'm sorry for not reacting to this issue.

Since @tmttn has been doing such a great job updating and maintaining the plugin, I'll archive this repository in favor of his fork.

Thanks for the excellent work, @tmttn!
